name: Backend CI

on:
  pull_request:
    paths: ['devops-final-be/**']

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops-final-be
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Install dependencies
        run: go mod tidy
        
      - name: Run Tests
        run: go test -v ./...
